# **EDA: Vista 360**

In [1]:
# --- librerias --- #

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import warnings

from pathlib import Path

# --- set cwd --- #
ROOT = Path().cwd().parent
os.chdir(ROOT)
pd.set_option("display.max_columns",None)
warnings.filterwarnings("ignore")

In [2]:
# --- Leemos el archivo de labels --- #

labels = (
    pd.read_parquet(
        r'data\raw\labels\labels_27-09-2026.parquet', 
        engine='pyarrow',
    )
    .drop(
        columns=['strEstadoInicial'], 
    )
)

# --- Leemos la vista 360 --- #
v360_ini = (
    pd.read_parquet(
        r'data\raw\features\v_360\v_360_27-09-2026.parquet', 
        engine='pyarrow',   
    )
)

In [3]:
# --- Realizamos un merge entre la vista 360 y los labels --- #

v360= (
    pd.merge(
        labels, 
        v360_ini, 
        how='left',
        on=['strPeriodo','strIdentificacion'],  
    )
    .drop(
        columns=['strIdentificacion', 'strPeriodo']
    )
)

v360.head()

,IndicadorReactivado,v360_skcliente,v360_Identificacion,v360_Estado,v360_Periodo,v360_IndInactivo,v360_Puntaje Acierta,v360_Puntaje Acierta Rango,v360_Regional,v360_Zona,v360_Oficina,v360_Genero,v360_Edad,v360_Rango Edad,v360_Antiguedad Actual (Años),v360_Antiguedad,v360_Tipo Vinculacion,v360_Estado Civil,v360_Estrato,v360_Nivel Academico,v360_Actividad Laboral,v360_Rango Ingresos,v360_numValorIngresos,v360_Tipo de Vivienda,v360_Area Conocimiento,v360_Segmento Ingresos vs. Antiguedad,v360_Segmento,v360_Menores a cargo,v360_Adultos a cargo,v360_Cuenta de Deposito,v360_Cuenta Juvenil,v360_Fondo de Vivienda,v360_Cuenta AFC,v360_Cheque Cuenta,v360_Tarjeta Debito,v360_CDT,v360_PAP,v360_Cupo Activo,v360_Credito Libre Inv sin Grtia,v360_Credito Libre Inv con Grtia,v360_Credito de Vivienda,v360_Credito de Vehiculo,v360_Credito Creacion de Empresa,v360_Credito de Educacion,v360_CrediMutual,v360_Otros Creditos,v360_Recaudo Pila,v360_Bancaseguros,v360_MasterCardCupo,v360_MasterCardSaldo,v360_Tarjeta Coomeva (Marca Propia) con saldo,v360_VISACupo,v360_VISASaldo,v360_Microcreditos,v360_Credisolidario,v360_Solidaridad Plan Basico,v360_Incrementos Plan Basico,v360_Libranza,v360_ReestructuracionConsumo,v360_COERotativo,v360_Originadores,v360_COE,v360_CupoEducar,v360_CreditoTurismo,v360_CreditoSaludBienestar,v360_ReestructuracionComercial,v360_ReestructuracionVivienda,v360_CreditoCapitaldeTrabajo,v360_Findeter,v360_Bancoldex,v360_Sobregiro,v360_CreditoCalamidad,v360_CreditoProductivo,v360_FindeterRotativo,v360_NominaFacil,v360_PagodeObligaciones,v360_Vida,v360_Vida Clasica,v360_Hospitalizacion,v360_Tranquilidad,v360_Recuperacion,v360_Exequial,v360_Solvencia,v360_Herencia,v360_Plan Educativo,v360_Seguros Auto,v360_SOAT,v360_Hogar Mas y Total Home,v360_Total RC Medica,v360_Otras polizas,v360_EPS,v360_Medicina Integral,v360_CEM,v360_Salud Oral,v360_numCantidadProductos,v360_ValorVida,v360_ValorPerseverancia,v360_ValorRenta,v360_Habeas Data,v360_ColaboradorGECC,v360_CantidadEventosRecreacion_Histo,v360_CantidadEventosRecreacionSinCosto_Histo,v360_CantidadEventosRecreacionConCosto_Histo,v360_ValorEventosRecreacionConCosto_Histo,v360_UltimoEventoRecreacionAsistio_Histo,v360_FechaUltimoEventoRecreacionAsistio_Histo,v360_CantidadEventosRecreacion_Ult_3Meses,v360_CantidadEventosRecreacionSinCosto_Ult_3Meses,v360_CantidadEventosRecreacionConCosto_Ult_3Meses,v360_ValorEventosRecreacionConCosto_Ult_3Meses,v360_CantidadEventosEducacion_Histo,v360_CantidadEventosEducacionSinCosto_Histo,v360_CantidadEventosEducacionConCosto_Histo,v360_ValorEventosEducacionConCosto_Histo,v360_UltimoEventoEducacionAsistio_Histo,v360_FechaUltimoEventoEducacionAsistio_Histo,v360_CantidadEventosEducacion_Ult_3Meses,v360_CantidadEventosEducacionSinCosto_Ult_3Meses,v360_CantidadEventosEducacionConCosto_Ult_3Meses,v360_ValorEventosEducacionConCosto_Ult_3Meses,v360_CantidadEventosFundacion_Histo,v360_CantidadEventosFundacionSinCosto_Histo,v360_CantidadEventosFundacionConCosto_Histo,v360_ValorEventosFundacionConCosto_Histo,v360_UltimoEventoFundacionAsistio_Histo,v360_FechaUltimoEventoFundacionAsistio_Histo,v360_CantidadEventosFundacion_Ult_3Meses,v360_CantidadEventosFundacionSinCosto_Ult_3Meses,v360_CantidadEventosFundacionConCosto_Ult_3Meses,v360_ValorEventosFundacionConCosto_Ult_3Meses,v360_cntPQRCoomeva,v360_cntPQRSalud,v360_cntPQREPS,v360_cntPQRFinanciero,v360_IntervaloValorVida,v360_IntervaloValorPerseverancia,v360_IntervaloValorRenta,v360_IntervalonumCantidadProductos,v360_CuotaCeroUno,v360_DebitoAutomatico,v360_CorrespondenciaVirtualoFisica,v360_Corte_Facturacion_Asociado,v360_Tipo Cliente,v360_Orden Antiguedad,v360_Orden Rango Ingresos,v360_Orden Rango Edad,v360_numCuoCan,v360_numCuoFac,v360_numCuoVen,v360_numEdadCartera,v360_PerfilNuevoAsociadoGH,v360_IndPrevinculado,v360_CuotasMoraBUC,v360_Desempleo,v360_ReservaMatematica,v360_Alerta_Habito_Pago_Externo,v360_Alerta_Estado_Creditos_Externos,v360_Alerta_Capacidad_Pago_Externo,v360_SaldoAportes,v360_SaldoSolidaridad,v360_Tipologia_Ciudad_Vinculacion,v360_Tipologia_Ciudad_Residencia,v360_Propension_Fuga_Asociado_Coomeva,v360_Score_Fuga_Asociado_Coomeva,v360_score,v360_Estrellas,v360_cartera,v360_generacion_valor,v360_salud_financiera_externa,v360_tenencia,v360_uso,v360_EstadoScore,v360_Nombre Asociado,v360_CodDaneCiudadResidencia,v360_CiudadResidencia,v360_CodDaneCiudadHomologada,v360_CiudadHomologada,v360_Rango_Score,v360_Cantidad_AliviosFinancieros_GECC,v360_Valor_Entregado_AliviosFinancieros_GECC,v360_Cantidad_AliviosFinancieros_Coomeva,v360_Valor_Entregado_AliviosFinancieros_Coomeva,v360_Cantidad_AliviosFinancieros_Bancoomeva,v360_Cantidad_AliviosFinancieros_MP,v360_Valor_Entregado_AliviosFinancieros_MP,v360_Cantidad_AliviosFinancieros_Corredor,v360_Valor_Entregado_AliviosFinancieros_Corredor,v360_Cantidad_AliviosFinancieros_Fundacion,v360_Valor_Entregado_AliviosFinancieros_Fundacion,v360_numvalBeneficiosGeccHisto,v360_numCantBeneficiosGeccHisto,v360_numCantPeriodosConBenefHisto,v360_ValorBeneficios_Financiero_Histo,v360_ValorBeneficios_Salud_Histo,v360_ValorBeneficios_Educacion_Histo,v360_ValorBeneficios_Fundacion_Histo,v360_ValorBeneficios_Coomeva_Histo,v360_ValorBeneficios_FondoSolidar_Histo,v360_ValorBeneficios_EducacionBonos_Histo,v360_ValorBeneficios_EducacionTasaCompen_Histo,v360_ValorBeneficios_CoomevaCuotaTAC_Histo,v360_ValorBeneficios_CoomevaFSVivienda_Histo,v360_ValorBeneficios_SaludMedIntegral_Histo,v360_ValorBeneficios_SaludSaludOral_Histo,v360_ValorBeneficios_SaludCEM_Histo,v360_ValorBeneficios_FinancieroProdAhorro_Histo,v360_ValorBeneficios_FinancieroProdCredito_Histo,v360_ValorBeneficios_FinancieroServicios_Histo,v360_ValorBeneficios_FondoSolidarJuridica_Histo,v360_ValorBeneficios_FondoSolidarPensional_Histo,v360_ValorBeneficios_FondoSolidarOpiMedica_Histo,v360_ValorBeneficios_FundacionMicrocreditos_Histo,v360_Beneficiarios solidaridad,v360_Beneficiarios solidaridad - hijos menores,v360_Beneficiarios solidaridad - hijos mayores,v360_Beneficiarios solidaridad - padres,v360_Beneficiarios solidaridad - conyugue,v360_Beneficiarios solidaridad - otro parentesco,v360_GrupoFamiliar,v360_FECHA_ACTIVACION_DEBITO_AUTOMATICO,v360_TIENE EL DEBITO AUTOMATICO AUTORIZADO,v360_TIPO_CUENTA,v360_NivelEndeudamientoExterno,v360_ValorBeneficiosGecc12Meses,v360_CantidadBeneficiosGecc12Meses,v360_CantidadPeriodosConBenef12Meses,v360_ValorBeneficios_Financiero_12Meses,v360_ValorBeneficios_Salud_12Meses,v360_ValorBeneficios_Educacion_12Meses,v360_ValorBeneficios_Fundacion_12Meses,v360_ValorBeneficios_Coomeva_12Meses,v360_ValorBeneficios_FondoSolidar_12Meses,v360_ValorBeneficios_EducacionBonos_12Meses,v360_ValorBeneficios_EducacionTasaCompen_12Meses,v360_ValorBeneficios_CoomevaCuotaTAC_12Meses,v360_ValorBeneficios_CoomevaFSVivienda_12Meses,v360_ValorBeneficios_SaludMedIntegral_12Meses,v360_ValorBeneficios_SaludSaludOral_12Meses,v360_ValorBeneficios_SaludCEM_12Meses,v360_ValorBeneficios_FinancieroProdAhorro_12Meses,v360_ValorBeneficios_FinancieroProdCredito_12Meses,v360_ValorBeneficios_FinancieroServicios_12Meses,v360_ValorBeneficios_FondoSolidarJuridica_12Meses,v360_ValorBeneficios_FondoSolidarPensional_12Meses,v360_ValorBeneficios_FondoSolidarOpiMedica_12Meses,v360_ValorBeneficios_FundacionMicrocreditos_12Meses,v360_Antigüedad_Producto_CrediSolidario,v360_Antigüedad_Producto_CrediAsociado,v360_Antigüedad_Producto_Microcreditos,v360_Antigüedad_Producto_Fondo_Social_Vivienda_Credito_Patrimonial,v360_Antigüedad_Producto_Autos,v360_Antigüedad_Producto_SOAT,v360_Antigüedad_Producto_Hogar,v360_Antigüedad_Producto_RCMedica,v360_Antigüedad_Producto_MP,v360_Antigüedad_Producto_SaludOral,v360_Antigüedad_Producto_CEM,v360_Antigüedad_Producto_Vida,v360_Antigüedad_Producto_VidaClasica,v360_Antigüedad_Producto_Desempleo,v360_Antigüedad_Producto_Hospitalizacion,v360_Antigüedad_Producto_Tranquilidad,v360_Antigüedad_Producto_Recuperacion,v360_Antigüedad_Producto_Exequial,v360_Antigüedad_Producto_Solvencia,v360_Antigüedad_Producto_Herencia,v360_Antigüedad_Producto_PlanEducativo,v360_Tipo_Cliente_Asociado,v360_Valor_FacturacionPromedio_GECC_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_GECC_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_GECC_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_GECC_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_GECC_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_GECC_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_GECC_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_GECC_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_GECC_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_GECC_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_GECC_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Aportes_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Aportes_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Aportes_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Aportes_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Aportes_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Aportes_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Aportes_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Aportes_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Aportes_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Aportes_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_Aportes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_AuxFunerario_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_AuxFunerario_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_AuxFunerario_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_AuxFunerario_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_AuxFunerario_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_AuxFunerario_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_AuxFunerario_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_AuxFunerario_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_AuxFunerario_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_AuxFunerario_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_AuxFunerario_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Calamidad_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Calamidad_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Calamidad_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Calamidad_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Calamidad_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Calamidad_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Calamidad_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Calamidad_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Calamidad_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Calamidad_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_Calamidad_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_ClubLosAndes_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_ClubLosAndes_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_ClubLosAndes_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_ClubLosAndes_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_ClubLosAndes_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_ClubLosAndes_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_ClubLosAndes_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_ClubLosAndes_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_ClubLosAndes_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_ClubLosAndes_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_ClubLosAndes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Creditos_Mes,v360_Valor_FacturacionPromedio_Coomeva_Creditos_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Creditos_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Creditos_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Creditos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Creditos_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Creditos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Creditos_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Creditos_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Creditos_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_Creditos_Ult3M,v360_Valor_FacturacionPromedio_Coomeva_Solidaridad_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Solidaridad_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Solidaridad_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Solidaridad_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Solidaridad_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Solidaridad_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Solidaridad_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Solidaridad_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Solidaridad_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Solidaridad_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_Solidaridad_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Seguros_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Seguros_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Seguros_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Seguros_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Seguros_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Seguros_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Seguros_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Seguros_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Seguros_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Seguros_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_Seguros_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Recreacion_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Recreacion_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Recreacion_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Recreacion_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Recreacion_Vencido_Ult3M,v360_Valor_RecaudoPromedio_Coomeva_Recreacion_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Recreacion_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Recreacion_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Recreacion_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_Recreacion_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_Recreacion_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_OtrosConceptos_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_OtrosConceptos_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_OtrosConceptos_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_OtrosConceptos_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_OtrosConceptos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_OtrosConceptos_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_OtrosConceptos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_OtrosConceptos_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_OtrosConceptos_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Coomeva_OtrosConceptos_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_OtrosConceptos_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Bancoomeva_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Bancoomeva_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Bancoomeva_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Bancoomeva_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Bancoomeva_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Creditos_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Creditos_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Creditos_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Bancoomeva_Creditos_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Bancoomeva_Creditos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Creditos_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Creditos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Creditos_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Bancoomeva_Creditos_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Bancoomeva_Creditos_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Bancoomeva_Creditos_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_CaptacionesyOtros_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_CaptacionesyOtros_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_CaptacionesyOtros_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Bancoomeva_CaptacionesyOtros_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Bancoomeva_CaptacionesyOtros_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_CaptacionesyOtros_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_CaptacionesyOtros_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_CaptacionesyOtros_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Bancoomeva_CaptacionesyOtros_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_Bancoomeva_CaptacionesyOtros_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_Bancoomeva_CaptacionesyOtros_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_MP_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_MP_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_MP_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_MP_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_MP_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Clasico_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Clasico_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Clasico_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_MP_Clasico_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_MP_Clasico_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Clasico_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Clasico_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Clasico_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_MP_Clasico_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_MP_Clasico_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_MP_Clasico_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Oro_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Oro_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Oro_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_MP_Oro_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_MP_Oro_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Oro_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Oro_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Oro_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_MP_Oro_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_MP_Oro_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_MP_Oro_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Plata_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Plata_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Plata_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_MP_Plata_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_MP_Plata_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Plata_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Plata_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Plata_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_MP_Plata_Ult_3Meses,v360_Cantidad_Periodos_Recaudo_MP_Plata_Vencido_Ult_3Meses,v360_Indice_RecaudoPromedio_MP_Plata_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Tradicional_Mes_Ult_3Meses,v36

In [ ]:
id_columns = ["skcliente",
              "Estado",
              "IndInactivo",
              "Regional",
              "Zona",
              "Oficina",
              "Area Conocimiento",
              "Habeas Data",
              "ColaboradorGECC",
              "Tipo Cliente",
              "Tipologia_Ciudad_Vinculacion",
              "Tipologia_Ciudad_Residencia",
              "Nombre Asociado",
              "CodDaneCiudadResidencia",
              "CiudadResidencia",
              "CodDaneCiudadHomologada",
              "CiudadHomologada",
              "dtmFechaInsercion",
              "dtmFechaActualizacionBI",
              "Alerta_ActualizacionDatos",
              "Fecha_Actualizacion_NPS_SAO",
              "Fecha_Actualizacion_NPS_MI",
              "TipoIdentificacion",
              "Turnos_En_Oficinas_UltimaOficinaVisitada_Ult12Meses",
              "Identificacion",
              "Periodo"]

PREFIJO = 'v360'

id_columns_pre = [f'{PREFIJO}_{col}' for col in id_columns] + ['strIdentificacion' , 'strPeriodo']

v360= (
    v360
    .drop(
        columns=id_columns_pre
    )
)

print(v360.shape[1])

792

## **Columnas CeroPapel -- Producto_Recomendado**

In [5]:
cero_papel_columns = [c for c in v360.columns if c.strip().__contains__("CeroPapel")]
producto_recomendado_columns = [c for c in v360.columns if c.strip().__contains__("Producto")]

columnas_eliminar = cero_papel_columns + producto_recomendado_columns

v360= (
    v360
    .drop(
        columns=columnas_eliminar
    )
)

In [6]:
v360.info()

<class 'pandas.DataFrame'>
RangeIndex: 997847 entries, 0 to 997846
Columns: 673 entries, IndicadorReactivado to v360_NombreArquetipo
dtypes: float64(417), int64(60), object(20), str(176)
memory usage: 5.8+ GB

## **Columnas Con un alto (%) de nulos**

In [7]:
# Se reemplazan vacios por np.nan para que pandas los reconozca como nulos y no como un string

VALORES_NULOS = ["", " ", "  ", "nan", "NaN", "NULL", "null", 
                 "N/A", "n/a", "NA", "ninguno", "NINGUNO", "-","Sin información"]

v360 = v360.replace(VALORES_NULOS,np.nan)

# Proporción de nulos x columna

pp_nulls = v360.isnull().mean()*100

threshold = 30 ## Columnas con el 30% o mas de nulos -- Eliminar

eliminar_80_nulos = pp_nulls.loc[pp_nulls >= threshold].index

v360 = v360[[c for c in v360.columns if c not in eliminar_80_nulos]]

v360.shape

(997847, 485)

## **Columnas Constantes**

In [8]:
col_constantes = [c for c in v360.columns 
                  if v360[c].nunique(dropna=True) <= 1]

v360 = v360[[c for c in v360.columns if c not in col_constantes]]

## **Columnas Cuasi Constantes**

In [9]:
cols_cuasi_constantes = [c for c in v360.columns
                         if v360[c].value_counts(normalize=True).iloc[0] >= 0.95]

col_cuasi_eliminar = [c for c in  cols_cuasi_constantes if c != 'IndicadorReactivado']

# --- Se validan tasas de reactivacion por valor --- #
def evaluar_candidatas(df, candidatas, target='IndicadorReactivado',
                       min_pos=50, lift_alto=2.0):
    base = df[target].mean()
    filas = []

    for col in candidatas:
        g = df.groupby(col, dropna=False)[target].agg(['size', 'sum'])
        g.columns = ['n', 'pos']
        moda = g['n'].idxmax()
        minoria = g.drop(index=moda)

        n_min   = minoria['n'].sum()
        pos_min = minoria['pos'].sum()
        tasa    = pos_min / n_min if n_min else 0
        lift    = tasa / base if base else 0

        filas.append({
            'columna': col,
            'pct_moda': g['n'].max() / len(df),
            'n_minoria': n_min,
            'pos_minoria': pos_min,
            'tasa_minoria': tasa,
            'lift_minoria': lift,
            'rescatar': (pos_min >= min_pos) and
                        (lift >= lift_alto)
        })

    return pd.DataFrame(filas).sort_values('lift_minoria', ascending=False)

evaluacion_cuasi = evaluar_candidatas(df=v360, candidatas=col_cuasi_eliminar,)

evaluacion_cuasi.loc[evaluacion_cuasi['rescatar'] == True].shape[0]

193

In [10]:
col_cuasi_eliminar = evaluacion_cuasi.loc[evaluacion_cuasi['rescatar'] == False, 'columna'].values

v360 = v360.drop(
    columns=col_cuasi_eliminar,
)

In [11]:

## Solo para las columnas numericas -- Se imputa temporalmente con mediana para calcular corr

v_360_num = v360.select_dtypes("number")
v_360_num_imp = v_360_num.fillna(v_360_num.median())

## Matriz de correlación

corr_matrix = v_360_num_imp.corr(method='spearman').abs()

UMBRAL_CORR = 0.95

## Columnas con correlación alta

upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

cols_alta_corr = [col for col in upper.columns if any(upper[col] > UMBRAL_CORR)]

cols_alta_corr

['v360_ValorEventosRecreacionConCosto_Histo',
 'v360_ValorEventosRecreacionConCosto_Ult_3Meses',
 'v360_CantidadEventosEducacionSinCosto_Histo',
 'v360_ValorEventosEducacionConCosto_Histo',
 'v360_CantidadEventosEducacionSinCosto_Ult_3Meses',
 'v360_CantidadEventosFundacionSinCosto_Histo',
 'v360_ValorEventosFundacionConCosto_Histo',
 'v360_Orden Antiguedad',
 'v360_Orden Rango Edad',
 'v360_Valor_Entregado_AliviosFinancieros_Corredor',
 'v360_numCantBeneficiosGeccHisto',
 'v360_numCantPeriodosConBenefHisto',
 'v360_ValorBeneficios_EducacionBonos_Histo',
 'v360_ValorBeneficios_CoomevaCuotaTAC_Histo',
 'v360_Valor_FacturacionPromedio_GECC_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_GECC_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_GECC_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Aportes_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Aportes_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Aportes_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_AuxFunerario_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Coomeva_AuxFunerario_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_AuxFunerario_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_AuxFunerario_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Calamidad_Mes_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Calamidad_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Calamidad_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Calamidad_Vencido_Ult_3Meses',
 'v360_Indice_RecaudoPromedio_Coomeva_Calamidad_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Creditos_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Creditos_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Coomeva_Creditos_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Coomeva_Creditos_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Creditos_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Solidaridad_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Coomeva_Solidaridad_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Solidaridad_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Solidaridad_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Seguros_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Coomeva_Seguros_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Coomeva_Seguros_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Seguros_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Seguros_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Recreacion_Mes_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Coomeva_Recreacion_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Recreacion_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Coomeva_Recreacion_Vencido_Ult_3Meses',
 'v360_Indice_RecaudoPromedio_Coomeva_Recreacion_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Bancoomeva_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Bancoomeva_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Bancoomeva_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Bancoomeva_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Bancoomeva_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_Bancoomeva_Creditos_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Bancoomeva_Creditos_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Bancoomeva_Creditos_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Bancoomeva_Creditos_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Bancoomeva_Creditos_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Bancoomeva_CaptacionesyOtros_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_Bancoomeva_CaptacionesyOtros_Vencido_Ult_3Meses',
 'v360_Valor_RecaudoPromedio_Bancoomeva_CaptacionesyOtros_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Bancoomeva_CaptacionesyOtros_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_Bancoomeva_CaptacionesyOtros_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_MP_Oro_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_Oro_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_Oro_Vencido_Ult_3Meses',
 'v360_Valor_RecaudoPromedio_MP_Oro_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_Oro_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_Oro_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_MP_Plata_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_Plata_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_Plata_Vencido_Ult_3Meses',
 'v360_Valor_RecaudoPromedio_MP_Plata_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_Plata_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_Plata_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_MP_Tradicional_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_Tradicional_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_MP_SAO_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_SAO_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_SAO_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_SAO_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_SAO_Vencido_Ult_3Meses',
 'v360_Valor_FacturacionPromedio_MP_OtrosConceptos_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_OtrosConceptos_Ult_3Meses',
 'v360_Cantidad_Periodos_Facturacion_MP_OtrosConceptos_Vencido_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_OtrosConceptos_Ult_3Meses',
 'v360_Cantidad_Periodos_Recaudo_MP_OtrosConceptos_Vencido_Ult_3Meses',
 'v360_Tiempo_Promedio_De_Espera_En_Oficinas_Ult12Meses',
 'v360_Tiempo_Promedio_De_Atencion_En_Oficinas_Ult12Meses',
 'v360_Tiempo_Promedio_Total_En_Oficinas_Ult12Meses']

In [12]:
## Eliminar las columnas alta correlación

v360 =  v360.drop(columns=cols_alta_corr)

v360.head()

,IndicadorReactivado,v360_Periodo,v360_Puntaje Acierta,v360_Puntaje Acierta Rango,v360_Genero,v360_Edad,v360_Rango Edad,v360_Antiguedad Actual (Años),v360_Antiguedad,v360_Tipo Vinculacion,v360_Estado Civil,v360_Estrato,v360_Nivel Academico,v360_Actividad Laboral,v360_Rango Ingresos,v360_numValorIngresos,v360_Tipo de Vivienda,v360_Segmento Ingresos vs. Antiguedad,v360_Segmento,v360_Menores a cargo,v360_Adultos a cargo,v360_Cuenta de Deposito,v360_Cuenta Juvenil,v360_Cuenta AFC,v360_Cheque Cuenta,v360_Tarjeta Debito,v360_CDT,v360_Cupo Activo,v360_Credito Libre Inv sin Grtia,v360_Credito de Vivienda,v360_Credito de Vehiculo,v360_Credito de Educacion,v360_CrediMutual,v360_Bancaseguros,v360_MasterCardSaldo,v360_VISACupo,v360_VISASaldo,v360_Credisolidario,v360_Solidaridad Plan Basico,v360_Incrementos Plan Basico,v360_ReestructuracionConsumo,v360_Vida,v360_Vida Clasica,v360_Hospitalizacion,v360_Tranquilidad,v360_Recuperacion,v360_Exequial,v360_Seguros Auto,v360_SOAT,v360_Hogar Mas y Total Home,v360_Total RC Medica,v360_Otras polizas,v360_Medicina Integral,v360_CEM,v360_Salud Oral,v360_ValorVida,v360_ValorPerseverancia,v360_ValorRenta,v360_CantidadEventosRecreacion_Histo,v360_CantidadEventosRecreacionSinCosto_Histo,v360_CantidadEventosRecreacionConCosto_Histo,v360_UltimoEventoRecreacionAsistio_Histo,v360_FechaUltimoEventoRecreacionAsistio_Histo,v360_CantidadEventosRecreacion_Ult_3Meses,v360_CantidadEventosRecreacionSinCosto_Ult_3Meses,v360_CantidadEventosRecreacionConCosto_Ult_3Meses,v360_CantidadEventosEducacion_Histo,v360_CantidadEventosEducacionConCosto_Histo,v360_FechaUltimoEventoEducacionAsistio_Histo,v360_CantidadEventosEducacion_Ult_3Meses,v360_CantidadEventosFundacion_Histo,v360_CantidadEventosFundacionConCosto_Histo,v360_FechaUltimoEventoFundacionAsistio_Histo,v360_cntPQRFinanciero,v360_IntervaloValorVida,v360_IntervaloValorPerseverancia,v360_CuotaCeroUno,v360_DebitoAutomatico,v360_Corte_Facturacion_Asociado,v360_Orden Rango Ingresos,v360_numEdadCartera,v360_PerfilNuevoAsociadoGH,v360_CuotasMoraBUC,v360_Desempleo,v360_SaldoAportes,v360_score,v360_Estrellas,v360_cartera,v360_generacion_valor,v360_salud_financiera_externa,v360_tenencia,v360_uso,v360_EstadoScore,v360_Rango_Score,v360_Cantidad_AliviosFinancieros_GECC,v360_Valor_Entregado_AliviosFinancieros_GECC,v360_Cantidad_AliviosFinancieros_Coomeva,v360_Valor_Entregado_AliviosFinancieros_Coomeva,v360_Cantidad_AliviosFinancieros_Bancoomeva,v360_Cantidad_AliviosFinancieros_MP,v360_Valor_Entregado_AliviosFinancieros_MP,v360_Cantidad_AliviosFinancieros_Corredor,v360_numvalBeneficiosGeccHisto,v360_ValorBeneficios_Financiero_Histo,v360_ValorBeneficios_Salud_Histo,v360_ValorBeneficios_Educacion_Histo,v360_ValorBeneficios_Coomeva_Histo,v360_ValorBeneficios_FondoSolidar_Histo,v360_ValorBeneficios_CoomevaFSVivienda_Histo,v360_ValorBeneficios_SaludMedIntegral_Histo,v360_ValorBeneficios_SaludCEM_Histo,v360_ValorBeneficios_FinancieroProdAhorro_Histo,v360_ValorBeneficios_FinancieroProdCredito_Histo,v360_ValorBeneficios_FinancieroServicios_Histo,v360_ValorBeneficios_FondoSolidarJuridica_Histo,v360_ValorBeneficios_FondoSolidarPensional_Histo,v360_Beneficiarios solidaridad,v360_Beneficiarios solidaridad - hijos menores,v360_Beneficiarios solidaridad - hijos mayores,v360_Beneficiarios solidaridad - padres,v360_Beneficiarios solidaridad - conyugue,v360_GrupoFamiliar,v360_TIENE EL DEBITO AUTOMATICO AUTORIZADO,v360_Tipo_Cliente_Asociado,v360_Valor_FacturacionPromedio_GECC_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_GECC_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_GECC_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_GECC_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_GECC_Ult_3Meses,v360_Indice_RecaudoPromedio_GECC_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Aportes_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Aportes_Vencido_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Aportes_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Aportes_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Aportes_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Aportes_Ult_3Meses,v360_Indice_RecaudoPromedio_Coomeva_Aportes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_AuxFunerario_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_AuxFunerario_Vencido_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_AuxFunerario_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_AuxFunerario_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_AuxFunerario_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_AuxFunerario_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Calamidad_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Calamidad_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Calamidad_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Calamidad_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Creditos_Mes,v360_Valor_RecaudoPromedio_Coomeva_Creditos_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Creditos_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Solidaridad_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Solidaridad_Vencido_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Solidaridad_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Solidaridad_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Solidaridad_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Solidaridad_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Seguros_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Seguros_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Seguros_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Seguros_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Seguros_Ult_3Meses,v360_Valor_FacturacionPromedio_Coomeva_Recreacion_Vencido_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Recreacion_Ult_3Meses,v360_Cantidad_Periodos_Facturacion_Coomeva_Recreacion_Vencido_Ult3M,v360_Valor_RecaudoPromedio_Coomeva_Recreacion_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Recreacion_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Coomeva_Recreacion_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Creditos_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_Creditos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Creditos_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Creditos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_Creditos_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_CaptacionesyOtros_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_CaptacionesyOtros_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_Bancoomeva_CaptacionesyOtros_Ult_3Meses,v360_Valor_RecaudoPromedio_Bancoomeva_CaptacionesyOtros_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Oro_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Oro_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Oro_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Oro_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Plata_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Plata_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Plata_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_Plata_Vencido_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_Tradicional_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_SAO_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_SAO_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_SAO_Mes_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_SAO_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_SAO_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_OtrosConceptos_Mes_Ult_3Meses,v360_Valor_FacturacionPromedio_MP_OtrosConceptos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_OtrosConceptos_Vencido_Ult_3Meses,v360_Valor_RecaudoPromedio_MP_OtrosConceptos_Ult_3Meses,v360_Grupo_Matriz_Inactivos,v360_CantidadAnios_InactividadAsociado,v360_Asociado_RiesgoExclusion,v360_Tipo_Cliente_Bancoomeva,v360_Tipo_Cliente_Prepagada,v360_Tipo_Cliente_CEM,v360_Tipo_Cliente_Seguros,v360_Tipo_Cliente_Adicionales,v360_CrediAsociado,v360_Tipo_Cliente_Cooperativa,v360_Segmento_Habito_Pago_Estatutario_3M,v360_Segmento_Habito_Pago_SyS_3M,v360_Segmento_Habito_Pago_Prepagada_3M,v360_Score_EnMora_Estatutaria,v360_Turnos_En_Oficinas_Total_Ult12Meses,v360_Turnos_En_Oficinas_Coomeva_Asesores_Integrales_Ult12Meses,v360_Turnos_En_Oficinas_Bancoomeva_Ult12Meses,v360_Turnos_En_Oficinas_Bancoomeva_FelicitacionesQuejasReclamos_Ult12Meses,v360_Turnos_En_Oficinas_Bancoomeva_Caja_Ult12Meses,v360_Turnos_En_Oficinas_Bancoomeva_Otros_Servicios_Ult12Meses,v360_Turnos_En_Oficinas_Salud_Asesores_De_Salud_Ult12Meses,v360_FondoSocialViviendaPatrimonial,v360_MicrosegmentoCicloDeVida,v360_CantIntencionRetiroCooperativa,v360_CantPeriodosInactivoUlt12meses,v360_CantPeriodosInactivoUlt6meses,v360_CantPeriodosInactivoUlt3meses,v360_InactivoMesAnterior,v360_CuotasVencidasEstatutaria,v360_ValorVencidoEstatutario,v360_Profesion
0,0,202506,0.0,[0 y Entre 541 y 750],F,36.0,[36-39] años,18.02,6 o más años,Familiar Asociado,Soltero,Estrato 6,Profesional,Independiente,(1.0 Mill-1.5 Mill],1125000.0,Familiar,Segmento E,Mujer Independiente,Ninguno,Ninguno,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10960663.0,10960663.0,10960.66,12,12,0,Bono Del 10 Descuento Andres Dc Bogota 2021,2021-05-27,0,0,0,0,0,1900-01-01,0,0,0,1900-01-01,0,[10-15 Mill),[10-15 Mill),Inactivo,Sin Débito Automático,Al 05 Del Mes,2,7.0,No aplica,20.0,0,0.0,34.0,2.0,80.0,25.0,6.0,5.0,6.0,Antiguos,Rango 2: [20-40) puntos,0,0.0,0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,Familia nuclear,NO,Solo Asociado,7347.0,602831.0,0.0,0.0,0.0,0.00,7347.0,0.0,0.0,0.0,0.0,0.0,290000.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18900.0,0.0,0.0,0.0,0.0,0.0,0.0,7347.0,230431.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,63500.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grupo 17,1,No,No,No,No,No,No,0,No,Muy Deficiente,Sin segmento,Sin segmento,Impago,0,0,0,0,0,0,0,0,Mujer Independiente,0,12,6,3,Si,21.0,524842.0,No Cruza
1,0,202506,771.0,>=751,F,42.0,[40-44] años,8.31,6 o más años,Profesional,Soltero,Estrato 3,Profesional,Independiente,Sin actualización de ingresos,2250000.0,Familiar,Sin Segmento,Transicion,Ninguno,Ninguno,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14904466.0,14904466.0,14904.00,1,1,0,Vn Programacion Armonica Vep Mayo Palmira 2022,2022-05-25,0,0,0,0,0,1900-01-01,0,1,0,2014-02-12,0,[10-15 Mill),[10-15 Mill),Inactivo,Sin Débito Automático,Al 15 Del Mes,8,7.0,Con Perfil,4.0,0,0.0,29.0,2.0,64.0,23.0,95.0,5.0,6.0,Inactivos,Rango 2: [20-40) puntos,0,0.0,0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,Familia nuclear,NO,Solo Asociado,21164.0,1894254.0,0.0,0.0,0.0,0.00,21164.0,0.0,0.0,0.0,0.0,0.0,191126.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10879.0,0.0,0.0,0.0,0.0,0.0,0.0,21164.0,1643703.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48546.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grupo 1,7,Si,No,No,No,No,No,0,No,Muy Deficiente,Sin segmento,Sin segmento,Impago,0,0,0,0,0,0,0,0,TransicionF,0,12,6,3,Si,90.0,1802070.0,FONOAUDIOLOGIA
2,0,202506,0.0,[0 y Entre 541 y 750],F,67.0,65 años o más,23.51,6 o más años,Mayor 60,Soltero,Estrato 1,Profesional,Asalariado,>4.0 Mill,10156864.0,Propia,Segmento F2,Maduro,1,Ninguno,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,27260550.0,0.00,7,7,0,Estrategia Virtual Septiembre Quibdo,2021-09-27,0,0,0,5,0,2012-11-17,0,2,0,2010-02-04,0,MENORES 5 Mill,[25-30 Mill),Inactivo,Con Débido Automático,Al 05 Del Mes,7,5.0,No aplica,12.0,0,0.0,33.0,2.0,67.0,26.0,36.0,40.0,6.0,Antiguos,Rango 2: [20-40) puntos,2,1500000.0,2,1500000.0,0,0,0.0,0,1714867.0,1422038.0,0.0,0.0,292829.0,0.0,0.0,0.0,0.0,0.0,1067674.0,354364.0,0.0,0.0,0,0,0,0,0,Familia nuclear,SI,Mixto Asociado/Bancoomeva/Seguros/Cooperativa,202496.0,2624305.0,0.0,0.0,0.0,0.00,202496.0,0.0,0.0,0.0,0.0,0.0,325000.0,3.0,0.0,0.0,0.0,0.0,0.0,62745.0,3.0,0.0,0.0,0.0,20655.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1306738.0,3.0,0.0,0.0,0.0,1778.0,18814.0,0.0,0.0,0.0,69395.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grupo 19,0,No,Si,No,No,Si,No,0,Si,Aceptable,Bueno,Sin segmento,Con Mora,11,6,4,0,4,0,0,0,Perseverados,0,6,6,3,Si,5.0,1328571.0,LICENCIADO
3,0,202506,782.0,>=751,M,37.0,[36-39] años,3.34,3 años,Técnicos y Tecnólogos,Soltero,Estrato 3,Técnico o Tecnólogo,Asalariado,>4.0 Mill,10323260.0,Familiar,Segmento F1,Transicion,Ninguno,Ninguno,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14000000.0,17000000.0,40614.00,2,2,0,Vn Programacion Virtual Recreacion Noviembre M...,2023-11-24,0,0,0,0,0,1900-01-01,0,0,0,1900-01-01,0,[10-15 Mill),[15-20 Mill),Inactivo,Sin Débito Automático,Al 05 Del Mes,7,4.0,Especial,4.0,0,991361.0,61.0,4.0,91.0,64.0,95.0,69.0,5.0,Nuevos,Rango 4: [60-80) puntos,0,0.0,0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,Familia nuclear,NO,Mixto Asociado/Bancoomeva,870137.0,804986.0,373606.0,745810.0,1119416.0,0.67,125337.0,0.0,136.0,136.0,0.0,35588.0,103403.0,3.0,0.0,136.0,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13038.0,0.0,0.0,0.0,0.0,0.0,0.0,70803.0,265280.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43800.0,3.0,3.0,0.0,0.0,0.0,1117200.0,569198.0,560409.0,1118512.0,1678920.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grupo 10,0,No,Si,No,No,No,No,0,No,Bueno,Aceptable,Sin segmento,Con Mora,8,2,6,0,4,1,0,0,TransicionM,0,1,1,1,No,4.0,563305.0,TECN EN ANALISIS Y DESARROLLO DE SISTEMAS DE I...
4,0,202506,851.0,>=751,F,45.0,[45-49] años,8.89,6 o más años,Profesional,Soltero,Estrato 6,Profesional,Independiente,Sin actualización de ingresos,2250000.0,Familiar,Sin Segmento,Consolidacion,[3-4],Ninguno,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15798734.0,15798734.0,166281.00,37,6,31,Convenio Registro Club Lake 2024,2024-03-21,0,0,0,0,0,1900-01-01,0,0,0,1900-01-01,0,[15-20 Mill),[15-20 Mill),Inactivo,Sin Débito Automático,Al 15 Del Mes,8,5.0,Con Perfil,4.0,0,0.0,22.0,2.0,40.0,62.0,67.0,5.0,7.0,Inactivos,Rango 2: [20-40) puntos,0,0.0,0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4,2,1,1,0,Familia extensa,NO,Solo Asociado,0.0,415050.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,325000.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20655.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69395.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grupo 17,0,No,No,No,No,No,No,0,No,Aceptable,Sin segmento,Sin segmento,Con Mora,0,0,0,0,0,0,0,0,Consolidacion,0,12,6,3,Si,5.0,325000.0,DERECHO

In [13]:
# --- Columnas eliminar x logica --- #

col_eliminar_logica = ["v360_Tipo_Cliente_Asociado",
                       "v360_UltimoEventoRecreacionAsistio_Histo",
                       "v360_DebitoAutomatico",
                       "v360_TIENE EL DEBITO AUTOMATICO AUTORIZADO",
                       "v360_Corte_Facturacion_Asociado",
                       "v360_Profesion",
                       ]

v360 = (
    v360
    .drop(
        columns=col_eliminar_logica, 
    )
)

## **Documentacion**

In [14]:
## Se genera un DataFrame -- documentación

v360_ini = v360_ini.replace(VALORES_NULOS,np.nan)

doc_vista_360 = pd.DataFrame({"Nombre_Columna":v360_ini.columns.tolist(),
                              "Tipo_Dato":v360_ini.dtypes,
                              "Cantidad_Nulos":v360_ini.isnull().mean().values,
                              }).reset_index(drop=True)

# --- Dataframe valores moda --- #

wrapper = {}

for c in v360_ini.columns:
    VALOR = round(v360_ini[c].value_counts(dropna=False,normalize=True).iloc[0], 2)
    wrapper[c] = VALOR
    
moda = (
    pd.DataFrame(
        {
            'Nombre_Columna': wrapper.keys(), 
            'FrecuenciaModa': wrapper.values()
        }
    )
)

doc_vista_360 = (
    doc_vista_360
    .merge(
        moda, 
        how='left', 
        on='Nombre_Columna'
    )
)

## Se generan comentarios

condiciones = [doc_vista_360["Nombre_Columna"].isin(id_columns_pre),
               doc_vista_360["Nombre_Columna"].isin(cero_papel_columns),
               doc_vista_360["Nombre_Columna"].isin(producto_recomendado_columns),
               doc_vista_360["Nombre_Columna"].isin(eliminar_80_nulos),
               doc_vista_360["Nombre_Columna"].isin(col_constantes),
               doc_vista_360["Nombre_Columna"].isin(col_cuasi_eliminar),
               doc_vista_360["Nombre_Columna"].isin(col_eliminar_logica),
               doc_vista_360["Nombre_Columna"].isin(cols_alta_corr)]

valores = ["Columna Identificadora",
           "Columna Cero Papel - No util",
           "Columna Producto Recomendado - No Util",
           "Alta Proporcion Nulos",
           "Columna Constante",
           "Columna Cuasi-Constante (90% mismo valor)",
           "Columna Eliminada por logica",
           "Columnas con 95% de correlacion"]

doc_vista_360["Decision"] = np.select(condlist=condiciones,
                                      choicelist=valores,
                                      default="Tener en cuenta")

doc_vista_360["Decision"].value_counts(normalize=True,
                                       dropna=False)

Decision
Tener en cuenta                              0.288509
Alta Proporcion Nulos                        0.229829
Columnas con 95% de correlacion              0.119804
Columna Cero Papel - No util                 0.103912
Columna Cuasi-Constante (90% mismo valor)    0.099022
Columna Constante                            0.079462
Columna Producto Recomendado - No Util       0.041565
Columna Identificadora                       0.030562
Columna Eliminada por logica                 0.007335
Name: proportion, dtype: float64

In [15]:
columnas_str = doc_vista_360[(doc_vista_360["Decision"] == "Tener en cuenta") &
                             (doc_vista_360["Tipo_Dato"] == "str")]["Nombre_Columna"]

## Cambiar tipos Identificacion y Periodo

doc_vista_360.loc[doc_vista_360["Nombre_Columna"].isin(["Identificacion",
                                                        "Periodo"]),"Tipo_Dato"] = "int"

## Cambiar Tipo_Dato -- binaria

columnas_binarias = [col for col in v360.columns if v360[col].nunique() <= 2]

doc_vista_360.loc[doc_vista_360["Nombre_Columna"].isin(columnas_binarias),
                  "Tipo_Dato"] = "binaria"

In [16]:
doc_vista_360["Tipo_Dato"] = doc_vista_360["Tipo_Dato"].astype(str)

# Reemplazar object with str

doc_vista_360["Tipo_Dato"] = doc_vista_360["Tipo_Dato"].replace("object",
                                   "str")

# **Eliminar columnas comunes con Demografica**

In [17]:
# ---- Leemos la demografica --- #

demo = (
    pd.read_parquet(
        r'data\raw\features\demografica\demografica_27-09-2026.parquet', 
        engine='pyarrow', 
    )
)

col_v360_demo = [col for col in v360.columns.str.capitalize().str.replace(" ",
                                                                       "_",
                                                                       regex=False).str.replace('v360_', 'demo_') if col in demo.columns]

In [18]:
v360.columns

Index(['IndicadorReactivado', 'v360_Periodo', 'v360_Puntaje Acierta',
       'v360_Puntaje Acierta Rango', 'v360_Genero', 'v360_Edad',
       'v360_Rango Edad', 'v360_Antiguedad Actual (Años)', 'v360_Antiguedad',
       'v360_Tipo Vinculacion',
       ...
       'v360_Turnos_En_Oficinas_Salud_Asesores_De_Salud_Ult12Meses',
       'v360_FondoSocialViviendaPatrimonial', 'v360_MicrosegmentoCicloDeVida',
       'v360_CantIntencionRetiroCooperativa',
       'v360_CantPeriodosInactivoUlt12meses',
       'v360_CantPeriodosInactivoUlt6meses',
       'v360_CantPeriodosInactivoUlt3meses', 'v360_InactivoMesAnterior',
       'v360_CuotasVencidasEstatutaria', 'v360_ValorVencidoEstatutario'],
      dtype='str', length=235)

In [19]:
col_in_demo = [
    'v360_Puntaje Acierta', 
    'v360_Genero', 
    'v360_Edad', 
    'v360_Rango Edad', 
    'v360_Antiguedad Actual (Años)', 
    'v360_Tipo Vinculacion',
    'v360_Puntaje Acierta Rango', 
    'v360_Estado Civil', 
    'v360_Nivel Academico', 
    'v360_Actividad Laboral', 
    'v360_Rango Ingresos', 
    'v360_numValorIngresos', 
    'v360_Tipo de Vivienda', 
    'v360_Segmento',
    'v360_Menores a cargo', 
    'v360_Adultos a cargo', 
    'v360_Estrato'
    
]

# --- Eliminar las columnas que ya estan presentes en demografica --- #

v360 = (
    v360
    .drop(
        columns=col_in_demo, 
    )
)


# Se agrega en la documentación -- Decision == "Columna Contenida en Demografica"

doc_vista_360["Decision"] = np.where(doc_vista_360["Nombre_Columna"].isin(col_in_demo), 
                                     'Columna Contenida en Demografica', 
                                     doc_vista_360["Decision"])

##Exportar la documentación 

doc_path = Path.cwd() / "docs"

doc_vista_360.to_excel(f"{doc_path}/doc_v360.xlsx",
                       index=False)

In [22]:
v360['v360_GrupoFamiliar'].value_counts()

v360_GrupoFamiliar
Familia nuclear    556372
Familia extensa    441475
Name: count, dtype: int64

In [21]:
## Se genera un .json -- columnas a tener en cuenta y dtypes

import json

json_vista = {"Columna":doc_vista_360[doc_vista_360["Decision"] == "Tener en cuenta"]["Nombre_Columna"].tolist(),
              "Tipo":doc_vista_360[doc_vista_360["Decision"] == "Tener en cuenta"]["Tipo_Dato"].tolist()}

ruta_salida = Path.cwd()/ "config" /"columns_360.json"


with open(file=ruta_salida, mode="w", encoding="utf-8") as writer:
    json.dump(json_vista,fp=writer,ensure_ascii=False,indent=4)